<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Promise.prototype.catch()</title>
</head>
<body>

    <h1>Promise.prototype.catch()</h1>

    MDN:
    <blockquote>
    The catch() method returns a Promise and deals with rejected cases only. It behaves the same as calling Promise.prototype.then(undefined, onRejected) (in fact, calling obj.catch(onRejected) internally calls obj.then(undefined, onRejected)). This means that you have to provide an onRejected function even if you want to fall back to an undefined result value - for example obj.catch(() => {}).
    </blockquote>

    <h2>Links</h2>
    MDN: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch">Promise.prototype.catch()</a>

    <hr>

    <h2>Demonstration</h2>

    <div id="target"></div>

</body>
<script>

    function wait(milliseconds) {
                                            // after the time out the callback "resolve" will be called, - that callback yields a fullfilled promise.
        return new Promise( resolve => window.setTimeout(resolve, milliseconds));
    }

    function errorHandler(value) {
        console.error("Promise failed with value " + value);
    }

    let element = document.getElementById("target");

    /*
    wait(1000)
    .then( () => { throw new Error("1")})
    //.catch( e => console.error(e) );
    /**/

    /*
    wait(2000)
    .then( () => { throw new Error("2") })
    .then( () => { element.append("3")  })
    .catch(e => console.error("error", e));
    /**/

    element.append(" 0 ");

</script>
</html>
